apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  flags: |
    {{- range .Values.security.appBlacklist }}
    --blacklist-app={{ . }}
    {{- end }}
    {{- range .Values.security.catalogBlacklist }}
    --blacklist-catalog={{ . }}
    {{- end }}
    {{- range .Values.security.groupWhitelist }}
    --whitelist-group={{ . }}
    {{- end }}
    {{- range .Values.security.namespaceBlacklist }}
    --blacklist-namespace={{ . }}
    {{- end }}
    {{- range .Values.security.userWhitelist }}
    --whitelist-user={{ . }}
    {{- end }}
