apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  {{- with .Values.deploymentStrategy }}
  strategy:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "labels.selector" . | nindent 20 }}
                topologyKey: kubernetes.io/hostname
              weight: 100
      volumes:
        - name: {{ include "name" . }}-certificates
          secret:
            secretName: {{ include "resource.default.name"  . }}-certificates
        {{- if .Values.psp.enableOverrides }}
        - name: psp-config-file
          configMap:
            name: {{ include "resource.default.name" .}}-psp-config
        {{- end }}
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        {{- with .Values.podSecurityContext}}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ include "name" . }}
          image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ include "image.tag" . }}"
          args:
            - ./app-admission-controller
            - --tls-cert-file=/certs/ca.crt
            - --tls-key-file=/certs/tls.key
            - --provider={{ .Values.provider.kind }}
            {{- if .Values.psp.enableOverrides }}
            - --psp-config-file=/etc/app-admission-controller/psp-config.yaml
            {{- end }}
            {{- range .Values.security.appBlacklist }}
            - --blacklist-app={{ . }}
            {{- end }}
            {{- range .Values.security.catalogBlacklist }}
            - --blacklist-catalog={{ . }}
            {{- end }}
            {{- range .Values.security.groupWhitelist }}
            - --whitelist-group={{ . }}
            {{- end }}
            {{- range .Values.security.namespaceBlacklist }}
            - --blacklist-namespace={{ . }}
            {{- end }}
            {{- range .Values.security.userWhitelist }}
            - --whitelist-user={{ . }}
            {{- end }}
          volumeMounts:
          - name: {{ include "name" . }}-certificates
            mountPath: "/certs"
          {{- if .Values.psp.enableOverrides }}
          - name: psp-config-file
            mountPath: "/etc/app-admission-controller"
          {{- end }}
          ports:
          - containerPort: 8443
            name: webhook
          - containerPort: 8080
            name: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 8443
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              cpu: 250m
              memory: 250Mi
          securityContext:
            {{- with .Values.securityContext }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
