image:
  name: "giantswarm/aws-admission-controller"
  tag: "[[ .Version ]]"

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deploymentStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

podDisruptionBudget:
  enabled: true
  minAvailable: 1
