image:
  name: "giantswarm/app-admission-controller"
  tag: "[[ .Version ]]"

Installation:
  V1:
    Registry:
      Domain: quay.io

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

deploymentStrategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate

podDisruptionBudget:
  enabled: true
  minAvailable: 1
